### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by 1scarecrow1** [1scarecrow1/skills-communicate-using-markdown#2]
- [X] Turn on GitHub Pages
- [X] Outline my portfolio
- [ ] Introduce myself to the world
